kind: ConfigMap
apiVersion: v1
metadata:
  name: bankconfig
  namespace: bank-ns
data:
  MYSQL_DATABASE: BankDB 
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-svc.bank-ns.svc.cluster.local:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root