---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: bankapp-ns
spec:
  type: LoadBalancer  # or NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: bankapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: "mysql-svc"   # The headless service for MySQL StatefulSet
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: banksecret
                  key: MYSQL_ROOT_USER  # Or set to "root" if not using a secret key
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banksecret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 80
